---
title: "長庚大學 大數據分析方法 作業六"
output: github_document
---


## 作業說明 （繳交時請直接刪除這個章節）

作業目的：期末專題暖身

依下列指示，完成期末分析專題作業規劃：

- 訂出分析問題，並將R Markdown的一級標題(第一行的title:)中的"長庚大學 大數據分析方法 作業六"取代為期末專題的分析問題，並在分析議題背景前加上組員姓名 (`10pt`)
- 分析議題背景 (`10pt`) 與動機 (`10pt`)
- 資料說明 (`10pt`) 與 載入 (`10pt`)
- 資料處理與清洗 (`10pt`) 說明 (`10pt`)
- 對資料們進行探索式資料分析，圖文並茂佳!(`20pt`)
- 期末專題分析規劃與假設 (`10pt`)

## 分析議題背景
背景介紹背景介紹

## 分析動機
分析動機分析動機

## 使用資料
說明使用資料們

載入使用資料們
```{r}
#這是R Code Chunk
library(readr)
atp_matches_1968 <- read_csv("D:/atp_datas/atp_matches_1968.csv")
atp_matches_1969 <- read_csv("D:/atp_datas/atp_matches_1969.csv")
atp_matches_1970 <- read_csv("D:/atp_datas/atp_matches_1970.csv")
atp_matches_1971 <- read_csv("D:/atp_datas/atp_matches_1971.csv")
atp_matches_1972 <- read_csv("D:/atp_datas/atp_matches_1972.csv")
atp_matches_1973 <- read_csv("D:/atp_datas/atp_matches_1973.csv")
atp_matches_1974 <- read_csv("D:/atp_datas/atp_matches_1974.csv")
atp_matches_1975 <- read_csv("D:/atp_datas/atp_matches_1975.csv")
atp_matches_1976 <- read_csv("D:/atp_datas/atp_matches_1976.csv")
atp_matches_1977 <- read_csv("D:/atp_datas/atp_matches_1977.csv")
atp_matches_1978 <- read_csv("D:/atp_datas/atp_matches_1978.csv")
atp_matches_1979 <- read_csv("D:/atp_datas/atp_matches_1979.csv")
atp_matches_1980 <- read_csv("D:/atp_datas/atp_matches_1980.csv")
atp_matches_1981 <- read_csv("D:/atp_datas/atp_matches_1981.csv")
atp_matches_1982 <- read_csv("D:/atp_datas/atp_matches_1982.csv")
atp_matches_1983 <- read_csv("D:/atp_datas/atp_matches_1983.csv")
atp_matches_1984 <- read_csv("D:/atp_datas/atp_matches_1984.csv")
atp_matches_1985 <- read_csv("D:/atp_datas/atp_matches_1985.csv")
atp_matches_1986 <- read_csv("D:/atp_datas/atp_matches_1986.csv")
atp_matches_1987 <- read_csv("D:/atp_datas/atp_matches_1987.csv")
atp_matches_1988 <- read_csv("D:/atp_datas/atp_matches_1988.csv")
atp_matches_1989 <- read_csv("D:/atp_datas/atp_matches_1989.csv")
atp_matches_1990 <- read_csv("D:/atp_datas/atp_matches_1990.csv")
atp_matches_1991 <- read_csv("D:/atp_datas/atp_matches_1991.csv")
atp_matches_1992 <- read_csv("D:/atp_datas/atp_matches_1992.csv")
atp_matches_1993 <- read_csv("D:/atp_datas/atp_matches_1993.csv")
atp_matches_1994 <- read_csv("D:/atp_datas/atp_matches_1994.csv")
atp_matches_1995 <- read_csv("D:/atp_datas/atp_matches_1995.csv")
atp_matches_1996 <- read_csv("D:/atp_datas/atp_matches_1996.csv")
atp_matches_1997 <- read_csv("D:/atp_datas/atp_matches_1997.csv")
atp_matches_1998 <- read_csv("D:/atp_datas/atp_matches_1998.csv")
atp_matches_1999 <- read_csv("D:/atp_datas/atp_matches_1999.csv")
atp_matches_2000 <- read_csv("D:/atp_datas/atp_matches_2000.csv")
atp_matches_2001 <- read_csv("D:/atp_datas/atp_matches_2001.csv")
atp_matches_2002 <- read_csv("D:/atp_datas/atp_matches_2002.csv")
atp_matches_2003 <- read_csv("D:/atp_datas/atp_matches_2003.csv")
atp_matches_2004 <- read_csv("D:/atp_datas/atp_matches_2004.csv")
atp_matches_2005 <- read_csv("D:/atp_datas/atp_matches_2005.csv")
atp_matches_2006 <- read_csv("D:/atp_datas/atp_matches_2006.csv")
atp_matches_2007 <- read_csv("D:/atp_datas/atp_matches_2007.csv")
atp_matches_2008 <- read_csv("D:/atp_datas/atp_matches_2008.csv")
atp_matches_2009 <- read_csv("D:/atp_datas/atp_matches_2009.csv")
atp_matches_2010 <- read_csv("D:/atp_datas/atp_matches_2010.csv")
atp_matches_2011 <- read_csv("D:/atp_datas/atp_matches_2011.csv")
atp_matches_2012 <- read_csv("D:/atp_datas/atp_matches_2012.csv")
atp_matches_2013 <- read_csv("D:/atp_datas/atp_matches_2013.csv")
atp_matches_2014 <- read_csv("D:/atp_datas/atp_matches_2014.csv")
atp_matches_2015 <- read_csv("D:/atp_datas/atp_matches_2015.csv")
atp_matches_2016 <- read_csv("D:/atp_datas/atp_matches_2016.csv")
atp_matches_2017 <- read_csv("D:/atp_datas/atp_matches_2017.csv")
atp_players <- read_csv("D:/atp_datas/atp_players.csv", 
    col_names = FALSE)
atp_rankings_70s <- read_csv("D:/atp_datas/atp_rankings_70s.csv", 
    col_names = FALSE)
atp_rankings_80s <- read_csv("D:/atp_datas/atp_rankings_80s.csv", 
    col_names = FALSE)
atp_rankings_90s <- read_csv("D:/atp_datas/atp_rankings_90s.csv", 
    col_names = FALSE)
atp_rankings_00s <- read_csv("D:/atp_datas/atp_rankings_00s.csv", 
    col_names = FALSE)
atp_rankings_10s <- read_csv("D:/atp_datas/atp_rankings_10s.csv", 
    col_names = FALSE)
atp_rankings_current <- read_csv("D:/atp_datas/atp_rankings_current.csv", 
    col_names = FALSE)
```

## 資料處理與清洗
說明處理資料的步驟

處理資料
```{r}
#這是R Code Chunk
```

## 探索式資料分析
圖文並茂圖文並茂
```{r}
#這是R Code Chunk
```

## 期末專題分析規劃
期末專題要做XXOOO交叉分析
